name: scientific-publications
channels:
  - conda-forge
  - defaults
  - esri
  - stcorp
dependencies:
  - alabaster=0.7.12=py_0
  - attrs=19.3.0=py_0
  - autopep8=1.5.1=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.4=pyh9f0ad1d_0
  - bqplot=0.12.6=pyh8c360ce_0
  - branca=0.3.1=py_0
  - brotlipy=0.7.0=py38h1e8a9f7_1000
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=3.1.1=py_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.0=py38ha419a9e_0
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.1=pyh8c360ce_0
  - colorama=0.4.3=py_0
  - colour=0.1.5=py_0
  - cryptography=2.8=py38hb32ad35_1
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.16=py38h32f6830_1
  - earthengine-api=0.1.218=pyh9f0ad1d_0
  - entrypoints=0.3=py38h32f6830_1001
  - folium=0.10.1=py_0
  - freetype=2.9.1=vc14_0
  - future=0.18.2=py38h32f6830_1
  - geemap=0.6.7=pyh9f0ad1d_0
  - ghp-import=1.0.0=pyh9f0ad1d_0
  - google-api-core=1.17.0=py38hc8b782b_0
  - google-api-python-client=1.8.0=pyh8c360ce_0
  - google-auth=1.14.0=pyh9f0ad1d_0
  - google-auth-httplib2=0.0.3=py_3
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.27.0=pyh9f0ad1d_0
  - google-resumable-media=0.5.0=py_1
  - googleapis-common-protos=1.51.0=py38hc8b782b_2
  - httplib2=0.17.2=pyh9f0ad1d_0
  - httplib2shim=0.0.3=pyh9f0ad1d_0
  - icu=64.2=he025d50_1
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.6.0=py38h32f6830_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.0=166
  - ipyfilechooser=0.3.4=pyh9f0ad1d_0
  - ipykernel=5.2.0=py38h5ca1d4c_1
  - ipyleaflet=0.12.4=pyh9f0ad1d_0
  - ipynb-py-convert=0.4.5=py_0
  - ipython=7.13.0=py38h32f6830_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py38h32f6830_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.7=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py38_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyter_highlight_selected_word=0.2.0=py38_1000
  - jupyter_latex_envs=1.4.4=py38_1000
  - jupyter_nbextensions_configurator=0.4.1=py38_0
  - jupytext=1.6.0=pyh9f0ad1d_0
  - kiwisolver=1.2.0=py38heaebd3c_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libiconv=1.15=hfa6e2cd_1006
  - liblapack=3.8.0=15_mkl
  - libpng=1.6.37=hfe6a214_1
  - libprotobuf=3.11.4=h1a1b453_0
  - libsodium=1.0.17=h2fa13f4_0
  - libtiff=4.1.0=h885aae3_6
  - libxml2=2.9.10=h9ce36c8_0
  - libxslt=1.1.33=heafd4d3_0
  - lxml=4.5.0=py38h7b22a32_1
  - lz4-c=1.9.2=h33f27b4_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=0.5.4=py_0
  - markupsafe=1.1.1=py38h9de7a3e_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py38h1626042_0
  - mistune=0.8.4=py38h9de7a3e_1001
  - mkl=2020.0=166
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.4=py_0
  - notebook=6.0.3=py38_0
  - numpy=1.18.1=py38ha749109_1
  - olefile=0.46=py_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.3=py38he6e81aa_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.1.1=py38h8103267_0
  - pip=20.0.2=py_2
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.11.4=py38h6fd17b8_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybtex=0.22.2=py38h32f6830_1
  - pybtex-docutils=0.2.2=py38h32f6830_1
  - pycodestyle=2.5.0=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h6538335_1
  - pyrsistent=0.16.0=py38h9de7a3e_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.2=h5fd99cc_6_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pywin32=227=py38hfa6e2cd_0
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.3.1=py38h9de7a3e_0
  - pyzmq=19.0.0=py38hc5dc6fd_1
  - qt=5.12.5=h7ef1ec2_0
  - requests=2.23.0=pyh8c360ce_2
  - rsa=4.0=py_0
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py38h32f6830_0
  - simplejson=3.17.0=py38hfa6e2cd_0
  - six=1.14.0=py_1
  - snowballstemmer=2.0.0=py_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-bibtex=1.0.0=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.30.1=hfa6e2cd_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hfa6e2cd_0
  - toml=0.10.1=pyh9f0ad1d_0
  - tornado=6.0.4=py38hfa6e2cd_0
  - traitlets=4.3.3=py38h32f6830_1
  - traittypes=0.2.1=py_1
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - vincent=0.4.4=py_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py38_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_1003
  - winpty=0.4.3=4
  - xarray=0.15.1=py_0
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.3=he774522_0
  - zeromq=4.3.2=h6538335_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=h9f78265_3
  - pip:
    - async-generator==1.10
    - beautifulsoup4==4.9.1
    - gitdb==4.0.5
    - gitpython==3.1.8
    - jupyter-book==0.8.1
    - jupyter-cache==0.4.1
    - jupyter-sphinx==0.3.1
    - libsass==0.20.1
    - myst-nb==0.10.1
    - myst-parser==0.12.9
    - nbclient==0.5.0
    - nbdime==2.0.0
    - nest-asyncio==1.4.0
    - oset==0.1.3
    - pydata-sphinx-theme==0.3.2
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - smmap==3.0.4
    - soupsieve==2.0.1
    - sphinx-book-theme==0.0.36
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.3.0
    - sphinx-panels==0.4.1
    - sphinx-thebe==0.0.7
    - sphinx-togglebutton==0.2.2
    - sqlalchemy==1.3.19
